[package]
name = "ibcm"
version = "0.1.0"
authors = ["Ian Johnson <ianprime0509@gmail.com>"]

[dependencies]
clap = "2.20.0"
error-chain = "0.7.2"

[[bin]]
doc = false
name = "ibcm"
path = "src/bin/ibcm.rs"
